###Instalando Bibliotecas

In [1]:
!pip install tmdbv3api

Collecting tmdbv3api
  Downloading tmdbv3api-1.7.6-py2.py3-none-any.whl (17 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from tmdbv3api) (2.23.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->tmdbv3api) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->tmdbv3api) (2021.10.8)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->tmdbv3api) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->tmdbv3api) (1.24.3)
Installing collected packages: tmdbv3api
Successfully installed tmdbv3api-1.7.6

###Importando Bibliotecas

In [2]:
import os, requests
import pandas as pd
from tmdbv3api import TMDb, Movie
from numpy import NaN

####Definindo parâmetros da API

In [3]:
tmdb = TMDb()
movie = Movie()
tmdb.api_key = 'c752658cbea631866744f576a4013cd1'

###Funções para localizar as Informações dos Filmes

####Pela biblioteca TMDbV3API

In [4]:
def get_id_movie(title_movie):
    res = movie.search(title_movie)
    return res[0].id

####Pela API da TMDb

In [5]:
def get_adult(movie_id):
    response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id, tmdb.api_key))
    data_json = response.json()
    return data_json['adult']

def get_belongs_to_collection(movie_id):
    response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id, tmdb.api_key))
    data_json = response.json()
    return data_json['belongs_to_collection']

def get_budget(movie_id):
    response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id, tmdb.api_key))
    data_json = response.json()
    return data_json['budget']

def get_genres(movie_id):
    response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id, tmdb.api_key))
    data_json = response.json()
    return data_json['genres']

def get_homepage(movie_id):
    response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id, tmdb.api_key))
    data_json = response.json()
    return data_json['homepage']

def get_imdb_id(movie_id):
    response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id, tmdb.api_key))
    data_json = response.json()
    return data_json['imdb_id']

def get_original_language(movie_id):
    response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id, tmdb.api_key))
    data_json = response.json()
    return data_json['original_language']

def get_overview(movie_id):
    response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id, tmdb.api_key))
    data_json = response.json()
    return data_json['overview']

def get_popularity(movie_id):
    response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id, tmdb.api_key))
    data_json = response.json()
    return data_json['popularity']

def get_poster_path(movie_id):
    response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id, tmdb.api_key))
    data_json = response.json()
    return data_json['poster_path']

def get_production_companies(movie_id):
    response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id, tmdb.api_key))
    data_json = response.json()
    return data_json['production_companies']

def get_production_countries(movie_id):
    response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id, tmdb.api_key))
    data_json = response.json()
    return data_json['production_countries']

def get_release_date(movie_id):
    response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id, tmdb.api_key))
    data_json = response.json()
    return data_json['release_date']

def get_revenue(movie_id):
    response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id, tmdb.api_key))
    data_json = response.json()
    return data_json['revenue']

def get_runtime(movie_id):
    response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id, tmdb.api_key))
    data_json = response.json()
    return data_json['runtime']

def get_spoken_languages(movie_id):
    response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id, tmdb.api_key))
    data_json = response.json()
    return data_json['spoken_languages']

def get_status(movie_id):
    response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id, tmdb.api_key))
    data_json = response.json()
    return data_json['status']

def get_tagline(movie_id):
    response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id, tmdb.api_key))
    data_json = response.json()
    return data_json['tagline']

def get_title(movie_id):
    response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id, tmdb.api_key))
    data_json = response.json()
    return data_json['title']

def get_video(movie_id):
    response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id, tmdb.api_key))
    data_json = response.json()
    return data_json['video']

def get_vote_average(movie_id):
    response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id, tmdb.api_key))
    data_json = response.json()
    return data_json['vote_average']
    
def get_vote_count(movie_id):
    response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id, tmdb.api_key))
    data_json = response.json()
    return data_json['vote_count']

def get_keywords(movie_id):
    response = requests.get('https://api.themoviedb.org/3/movie/{}/keywords?api_key={}'.format(movie_id, tmdb.api_key))
    data_json = response.json()
    try:
      return data_json['keywords']
    except:
      return NaN

def get_cast(movie_id):
    response = requests.get('https://api.themoviedb.org/3/movie/{}/credits?api_key={}'.format(movie_id, tmdb.api_key))
    data_json = response.json()
    return data_json['cast']

def get_crew(movie_id):
    response = requests.get('https://api.themoviedb.org/3/movie/{}/credits?api_key={}'.format(movie_id, tmdb.api_key))
    data_json = response.json()
    return data_json['crew']

###Criando a lista dos filmes de 2018 a 2021
Importante passo pois no arquivo CSV temos somente as informações anteriores a 2018

In [6]:
urls = ['https://en.wikipedia.org/wiki/List_of_American_films_of_2018', 
'https://en.wikipedia.org/wiki/List_of_American_films_of_2019', 
'https://en.wikipedia.org/wiki/List_of_American_films_of_2020',
'https://en.wikipedia.org/wiki/List_of_American_films_of_2021',
'https://en.wikipedia.org/wiki/List_of_American_films_of_2022']

df_concat = pd.DataFrame({})
for i in range(4):
    for j in range(2,7):
        df = pd.read_html(str(urls[i]), header = 0)[j]
        df_concat = pd.concat([df_concat, df], ignore_index=True)

df_concat = df_concat.filter(['Title'], axis = 1)

###Tratando os Dados
Ajustando nome das colunas, dados faltantes e filmes com o nome errado

In [7]:
df_concat.replace(regex={r'The SpongeBob Movie: Sponge on the Run.*':'The SpongeBob Movie: Sponge on the Run'}, inplace= True)
df_concat.replace(regex={r'Finding(.){7}':'Finding Ohana'}, inplace= True)
df_concat = df_concat[df_concat['Title'].notna()]

df_concat.rename(columns={'Title':'original_title'}, inplace= True)

###Buscando as informações dos Filmes de 2018 a 2021

####ID (pela biblioteca TMDbV3API

In [8]:
df_concat['id'] = df_concat['original_title'].map(lambda x: get_id_movie(str(x)))

####Outras informações pela API da TMDb

In [10]:
df_concat['adult'] = df_concat['id'].map(lambda x: get_adult(x))
df_concat['belongs_to_collection'] = df_concat['id'].map(lambda x: get_belongs_to_collection(x))
df_concat['budget'] = df_concat['id'].map(lambda x: get_budget(x))
df_concat['genres'] = df_concat['id'].map(lambda x: get_genres(x))
df_concat['homepage'] = df_concat['id'].map(lambda x: get_homepage(x))
df_concat['imdb_id'] = df_concat['id'].map(lambda x: get_imdb_id(x))
df_concat['original_language'] = df_concat['id'].map(lambda x: get_original_language(x))
df_concat['overview'] = df_concat['id'].map(lambda x: get_overview(x))
df_concat['popularity'] = df_concat['id'].map(lambda x: get_popularity(x))
df_concat['poster_path'] = df_concat['id'].map(lambda x: get_poster_path(x))
df_concat['production_companies'] = df_concat['id'].map(lambda x: get_production_companies(x))
df_concat['production_countries'] = df_concat['id'].map(lambda x: get_production_countries(x))
df_concat['release_date'] = df_concat['id'].map(lambda x: get_release_date(x))
df_concat['revenue'] = df_concat['id'].map(lambda x: get_revenue(x))
df_concat['runtime'] = df_concat['id'].map(lambda x: get_runtime(x))
df_concat['spoken_languages'] = df_concat['id'].map(lambda x: get_spoken_languages(x))
df_concat['status'] = df_concat['id'].map(lambda x: get_status(x))
df_concat['tagline'] = df_concat['id'].map(lambda x: get_tagline(x))
df_concat['title'] = df_concat['id'].map(lambda x: get_title(x))
df_concat['video'] = df_concat['id'].map(lambda x: get_video(x))
df_concat['vote_average'] = df_concat['id'].map(lambda x: get_vote_average(x))
df_concat['vote_count'] = df_concat['id'].map(lambda x: get_vote_count(x))
df_concat['keywords'] = df_concat['id'].map(lambda x: get_keywords(x))
df_concat['cast'] = df_concat['id'].map(lambda x: get_cast(x))
df_concat['crew'] = df_concat['id'].map(lambda x: get_crew(x))

In [11]:
df_concat.head()

,original_title,id,adult,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,overview,...,spoken_languages,status,tagline,title,video,vote_average,vote_count,keywords,cast,crew
0,Insidious: The Last Key,406563,False,"{'id': 228446, 'name': 'Insidious Collection',...",10000000,"[{'id': 27, 'name': 'Horror'}, {'id': 9648, 'n...",http://www.insidiousmovie.com,tt5726086,en,Parapsychologist Elise Rainier and her team tr...,...,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Fear comes home.,Insidious: The Last Key,False,6.2,2205,"[{'id': 2723, 'name': 'medium'}, {'id': 2849, ...","[{'adult': False, 'gender': 1, 'id': 7401, 'kn...","[{'adult': False, 'gender': 1, 'id': 494, 'kno..."
1,The Strange Ones,426258,False,None,0,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://thestrangeones.com/,tt6014904,en,Mysterious events surround the travels of two ...,...,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,,The Strange Ones,False,5.5,62,"[{'id': 380, 'name': 'sibling relationship'}, ...","[{'adult': False, 'gender': 2, 'id': 61363, 'k...","[{'adult': False, 'gender': 1, 'id': 17450, 'k..."
2,Stratton,348389,False,None,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",http://www.gfmfilms.co.uk/stratton,tt3567666,en,A British Special Boat Service commando tracks...,...,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,The enemy has a weapon. So do we.,Stratton,False,5.0,175,"[{'id': 818, 'name': 'based on novel or book'}...","[{'adult': False, 'gender': 2, 'id': 55470, 'k...","[{'adult': False, 'gender': 1, 'id': 10496, 'k..."
3,Sweet Country,468210,False,None,0,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",https://bunyaproductions.com.au/sweet-country/,tt6958212,en,"It’s 1929 on the vast, desert-like, Eastern Ar...",...,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Justice itself is put on trial,Sweet Country,False,6.5,136,"[{'id': 570, 'name': 'rape'}, {'id': 2831, 'na...","[{'adult': False, 'gender': 2, 'id': 1887857, ...","[{'adult': False, 'gender': 0, 'id': 55906, 'k..."
4,The Commuter,399035,False,None,30000000,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",https://thecommuter.movie/,tt1590193,en,"A businessman, on his daily commute home, gets...",...,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Lives are on the line,The Commuter,False,6.3,3716,"[{'id': 10410, 'name': 'conspiracy'}, {'id': 1...","[{'adult': False, 'gender': 2, 'id': 3896, 'kn...","[{'adult': False, 'gender': 2, 'id': 7230, 'kn..."

###Carregando o DataSet dos Filmes

In [77]:
df_movies = pd.read_csv('/content/movies_metadata.csv')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

####Fazendo um Merge do DataSet do Filme com o DataSet das Keywords e dos Créditos

In [78]:
df_credits = pd.read_csv('/content/credits.csv')
df_keywords = pd.read_csv('/content/keywords.csv')

In [79]:
df_movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [80]:
for i in df_movies['id']:
  try:
    int(i)
  except:
    print(i)

1997-08-20
2012-09-29
2014-01-01

In [81]:
df_movies.loc[df_movies['id'] == '1997-08-20']

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
19730,- Written by Ørnås,0.065736,/ff9qCepilowshEtG2GYWwzt2bs4.jpg,"[{'name': 'Carousel Productions', 'id': 11176}...","[{'iso_3166_1': 'CA', 'name': 'Canada'}, {'iso...",1997-08-20,0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [82]:
df_movies.loc[df_movies['id'] == '2012-09-29']

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
29503,Rune Balot goes to a casino connected to the ...,1.931659,/zV8bHuSL6WXoD6FWogP9j4x80bL.jpg,"[{'name': 'Aniplex', 'id': 2883}, {'name': 'Go...","[{'iso_3166_1': 'US', 'name': 'United States o...",2012-09-29,0,68.0,"[{'iso_639_1': 'ja', 'name': '日本語'}]",Released,...,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [83]:
df_movies.loc[df_movies['id'] == '2014-01-01']

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
35587,Avalanche Sharks tells the story of a bikini ...,2.185485,/zaSf5OG7V8X8gqFvly88zDdRm46.jpg,"[{'name': 'Odyssey Media', 'id': 17161}, {'nam...","[{'iso_3166_1': 'CA', 'name': 'Canada'}]",2014-01-01,0,82.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,...,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [84]:
df_movies.drop(labels=[19730,29503, 35587], axis = 0, inplace = True)

In [85]:
df_movies['id'] = df_movies['id'].astype('int64')

In [86]:
df_movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 45463 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45463 non-null  object
 1   belongs_to_collection  4491 non-null   object
 2   budget                 45463 non-null  object
 3   genres                 45463 non-null  object
 4   homepage               7779 non-null   object
 5   id                     45463 non-null  int64
 6   imdb_id                45446 non-null  object
 7   original_language      45452 non-null  object
 8   original_title         45463 non-null  object
 9   overview               44509 non-null  object
 10  popularity             45460 non-null  object
 11  poster_path            45077 non-null  object
 12  production_companies   45460 non-null  object
 13  production_countries   45460 non-null  object
 14  release_date           45376 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), int64(1), object(19)
memory usage: 8.7+ MB

In [87]:
df_credits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45476 entries, 0 to 45475
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   cast    45476 non-null  object
 1   crew    45476 non-null  object
 2   id      45476 non-null  int64
dtypes: int64(1), object(2)
memory usage: 1.0+ MB

In [88]:
df_keywords.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46419 entries, 0 to 46418
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        46419 non-null  int64
 1   keywords  46419 non-null  object
dtypes: int64(1), object(1)
memory usage: 725.4+ KB

In [89]:
df_merged = df_keywords.merge(df_credits, how='left', on='id')

In [90]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 46496 entries, 0 to 46495
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        46496 non-null  int64
 1   keywords  46496 non-null  object
 2   cast      46496 non-null  object
 3   crew      46496 non-null  object
dtypes: int64(1), object(3)
memory usage: 1.8+ MB

In [92]:
df_movies = df_movies.merge(df_merged, on='id', how='left')

In [93]:
df_movies.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,spoken_languages,status,tagline,title,video,vote_average,vote_count,keywords,cast,crew
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0,"[{'id': 931, 'name': 'jealousy'}, {'id': 4290,...","[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de..."
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0,"[{'id': 10090, 'name': 'board game'}, {'id': 1...","[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de..."
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0,"[{'id': 1495, 'name': 'fishing'}, {'id': 12392...","[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de..."
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0,"[{'id': 818, 'name': 'based on novel'}, {'id':...","[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de..."
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0,"[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...","[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de..."

###Concatenando os DataFrames

In [94]:
df_final = pd.concat([df_movies, df_concat], ignore_index=True)

###Exportando o DataFrame Concatenado

In [95]:
df_final.to_csv('df_final.csv', index = False, header = True)